name: Trigger Multiple Workflows in Repo B

on:
  push:
    branches:
      - dev

env:
  WORKFLOWS_TO_TRIGGER: dispatch2.yml,dispatch.yml
  TARGET_REPO: AniketD89/CalledRepo
  TARGET_BRANCH: dev

jobs:
  trigger-multiple-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger multiple workflows
        run: |
          set -e
          IFS=',' read -ra WORKFLOWS <<< "${WORKFLOWS_TO_TRIGGER}"
          for workflow in "${WORKFLOWS[@]}"; do
            trimmed=$(echo "$workflow" | xargs)
            echo "Triggering workflow: $trimmed"
            response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
              "https://api.github.com/repos/${TARGET_REPO}/actions/workflows/${trimmed}/dispatches" \
              -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              -d "{\"ref\":\"${TARGET_BRANCH}\"}")
            echo "HTTP response for $trimmed: $response"
            if [[ "$response" != "204" ]]; then
              echo "Failed to trigger $trimmed"
            fi
          done
